# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
import torch

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
x = torch.rand(7,7)
x
# Create random tensor


tensor([[0.5151, 0.6630, 0.7678, 0.1129, 0.7938, 0.5950, 0.8589],
        [0.7903, 0.2844, 0.9488, 0.7125, 0.6674, 0.3846, 0.2336],
        [0.9925, 0.7370, 0.1484, 0.5694, 0.7548, 0.3354, 0.8668],
        [0.9356, 0.8911, 0.3133, 0.5452, 0.0413, 0.7867, 0.4583],
        [0.2666, 0.1563, 0.4127, 0.1273, 0.7042, 0.9174, 0.8831],
        [0.0889, 0.4080, 0.4353, 0.4431, 0.9403, 0.8428, 0.7119],
        [0.1836, 0.0396, 0.4682, 0.7771, 0.3027, 0.2773, 0.5680]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
y = x @ torch.rand(1,7).T
y
# Perform matrix multiplication 


tensor([[2.3133],
        [2.2250],
        [2.3771],
        [1.7784],
        [1.9711],
        [2.0361],
        [1.3272]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
z= torch.mm(torch.rand(7,7), torch.rand(1,7).T) 
z
# Matrix multiply tensors


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

x = torch.rand(2,3).to('cuda')
y = torch.rand(2,3).to('cuda')

# Check for access to GPU

# Create two random tensors on GPU
x,y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
z = torch.mm(x,y.T)

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
z.max(), z.min()
# Find min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max

z.argmax(), z.argmin()
# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

z = torch.rand(1,1,1,10)
print(f'the shape is {z.shape} and it looks like {z}')
z2 = torch.squeeze(z)
print(f'the shape is {z2.shape} and it looks like {z2}')
# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes


the shape is torch.Size([1, 1, 1, 10]) and it looks like tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
the shape is torch.Size([10]) and it looks like tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
